name: Enique OS CI/CD
run-name: Build & Test project by @${{ github.actor }}

on:
  push:
    branches:
      - feature
      - release
      - production

    paths-ignore:
      - "README.md"
      - "assets/**"

  pull_request:
    branches:
      - feature
      - main
      - release
      - production

    paths-ignore:
      - "README.md"
      - "assets/**"

  workflow_dispatch:
    inputs:
      test_with:
        description: "What Virtualization tool to test project?"
        required: true
        default: "bochs"
        type: choice
        options:
          - bochs
          - qemu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show OS Info
        run: cat /etc/lsb-release

      - name: Clean some file
        run: |
          echo Run make clean
          make clean

      - name: Install Packages
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install nasm -y

      - name: Build
        run: |
          chmod 777 -R ./ImageMaker
          make all

      - name: Test
        run: |
          sudo apt install qemu-system-x86 bochs
          make run
          sudo apt-get install imagemagick -y

      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: "desktop.jpg"
