name: OS Auto Build
run-name: Build Enique OS by @${{ github.actor }}

on:
  push:
    branches: 
      - feature
      - release
      - production
      
    paths:
      - '!*'
      - '!docs/**'
      
  pull_request:
    branches:
      - feature
      - main
      - release
      - production
      
    paths:
      - '!*'
      - '!docs/**'

  workflow_dispatch:

env:
  foo: bar

defaults:
  run:
    shell: bash
    working-directory: scripts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show OS Info
        run: cat /etc/lsb-release

      - name: Clean some file
        run: |
          echo Run make clean
          make clean
        
      - name: Build
        run: make all
